### ISSUE TITLE
Research font

### ISSUE THREAD

**Issue by benwbrum** [SlaveryImages/SlaveryImages.org#30]
Merope is an example. Should support Yoruba or Fulani character set.

**Comment by saracarl** [comment]
Merope Basic

**Comment by saracarl** [comment]
The the only web font I've found called Merope-anything is this one:
https://www.fontshop.com/families/pleiad/merope
And I don't think it's what you had in mind.  

I think the Merope Basic font you referenced is a print font only.

I did find a family of AfroRoman fonts, here:  https://www.linguistsoftware.com/afrou.htm that support African characters.   Scroll down to "font samples".  Unfortunately, using a commercial, specialized font is not a feasible solution for widely read webpages.  (See https://www.linguistsoftware.com/faq-gen.htm#G13)

@henlovejoy  What other fonts do you use in your work, especially online or locally on your computer?

**Comment by henlovejoy** [comment]
For fonts I think that we don't need to focus on African characters immediately since there are none yet. So, I am really open to whichever font. Open source will be best, of course. I will be happy with one that has good operability across the browsers.

**Comment by benwbrum** [comment]
From the meeting: let's just use Helvetica.
