### ISSUE TITLE
Locate missing images

### ISSUE THREAD

**Issue by benwbrum** [SlaveryImages/SlaveryImages.org#43]
Several images were missing, so items were not created for them.  These can be found in the import log.

**Comment by benwbrum** [comment]
See import log, attached.  (Note that we can easily extract these as a spreadsheet.)
[import_log.txt](https://github.com/SlaveryImages/SlaveryImages.org/files/2520143/import_log.txt)

**Comment by benwbrum** [comment]
[missing.txt](https://github.com/SlaveryImages/SlaveryImages.org/files/2534474/missing.txt)

**Comment by benwbrum** [comment]
[tiffs_on_server.txt](https://github.com/SlaveryImages/SlaveryImages.org/files/2534541/tiffs_on_server.txt)

**Comment by benwbrum** [comment]
Files which were still not found in the log for job 29: [retry_missing.txt](https://github.com/SlaveryImages/SlaveryImages.org/files/2539786/retry_missing.txt)

**Comment by benwbrum** [comment]
[successes.txt](https://github.com/SlaveryImages/SlaveryImages.org/files/2572837/successes.txt)
We have no loaded all but around 200 images. 

The successful image which were loaded are in this list:

**Comment by benwbrum** [comment]
Some items have been imported successfully, but do not contain associated media files.  Many of these are duplicated, since they did not fail on import.

To review and upload:

- [x] Advertisement for Slave Sale, New Orleans, May 13, 1835
- [x] African Mule Driver, Peru, 1600-1615
- [x] Africans Forced to Dance on Deck of Slave Ship, early 19th cent.
- [x] Afro-Brazilian Dance, Rio de Janeiro, Brazil, 1820-24
- [x] Afro-Brazilian Dance, Rio de Janeiro, Brazil, 1820-24
- [x] Canoe for Transporting Slaves, Sierra Leone, 1840s
- [x] Capoeira Scene, Brazil, 1820-24
- [x] Capoeira Scene, Brazil, 1820-24
- [x] Cross-section of French Slave Ship Aurore, 1784
- [x] Crossing a Bridge, Western Sudan, 1790s
- [x] Executed Slaves, Demerara (British Guiana), 1823
- [x] Extracting a Chigger, Brazil, 1820-24
- [x] Extracting a Chigger, Brazil, 1820-24
- [x] French Slave Ship Vigilante, 1822
- [x] Hold of Brazilian Slave Ship, 1845
- [x] King of Benin (Oba) in procession, late 17th cent.
- [x] Maroons Ambushing British Troops, Jamaica, late 18th cent
- [x] Olaudah Equiano/Gustavas Vassa, 1789
- [x] Portrait of Rita, Rio de Janeiro, Brazil, 1820-24
- [x] Portrait of Rita, Rio de Janeiro, Brazil, 1820-24
- [x] Rescued Africans on Deck of British Naval Vessel, 1845
- [x] Revolt Aboard Slave Ship, 1787
- [x] Shackles on Slave Ship Henrietta Marie, 1700
- [x] Shackles Recovered from Slave Ship Henrietta Marie, 1700
- [x] Ship's Bell Recovered from Slave Ship Henrietta Marie, 1700
- [x] Slave Ship Henrietta Marie, 1699
- [x] Slave Ship Henrietta Marie, 1699/1700
- [x] Slave Ship Henrietta Marie, 1700
- [x] Slaves Waiting for Sale, Richmond, Virginia, 1861
- [x] Slaves Waiting for Sale, Richmond, Virginia, 1861
- [x] Sleeping Positions of Captive Africans on the French Slave Ship Aurore, 1784
- [x] Sugar Curing House, 1762
- [x] The British Slave Ship Brookes, 1789
- [x] Tobacco Warehouse, Richmond, Virginia, 1865
- [x] Top Deck of French Slave Ship, 19th cent.
- [x] Whipping of a Fugitive Slave, French West Indies, 1840s
- [x] Whipping of a Fugitive Slave, French West Indies, 1840s

**Comment by benwbrum** [comment]
In the batch above, no file exists for:

* _Crossing a Bridge, Western Sudan, 1790s_, image 338a
* _Executed Slaves, Demerara (British Guiana), 1823_, image BRLIB-1
* _Maroons Ambushing British Troops, Jamaica, late 18th cent_, image BRLIB-2
* _Tobacco Warehouse, Richmond, Virginia, 1865_, image 09_709
* _Slaves Waiting for Sale, Richmond, Virginia, 1861_, image Image-1.tif
* _Sugar Curing House, 1762_, image affinerie_des_sucres
* _Whipping of a Fugitive Slave, French West Indies, 1840s_, image Image-2.tif

**Comment by benwbrum** [comment]
List of images we successfully loaded is attached.
[good_files.txt](https://github.com/SlaveryImages/SlaveryImages.org/files/2587302/good_files.txt)

**Comment by henlovejoy** [comment]
Thanks Ben,
Doesn’t seem so bad. 
HL

**Comment by benwbrum** [comment]
There is a new folder called Missing Images in the google drive.  We should upload and ingest them.
