### ISSUE TITLE
landing page content

### ISSUE THREAD

**Issue by benwbrum** [SlaveryImages/SlaveryImages.org#45]
figure out what you see

**Comment by henlovejoy** [comment]
https://hlovejoy.wordpress.com/annaberg-plantation-st-john-island/ <https://hlovejoy.wordpress.com/annaberg-plantation-st-john-island/>

**Comment by benwbrum** [comment]
Consider rotating slide-show for the landing page.

**Comment by benwbrum** [comment]
search after the slideshow.  Consider browability right under search

**Comment by benwbrum** [comment]
Consider:
* Slideshow + "about" text
* search form
* item set list like [old site "Explore" page](http://www.slaveryimages.org/search.html)

**Comment by benwbrum** [comment]
No slideshow/carousel needed.
