### ISSUE TITLE
Clean duplicate items

### ISSUE THREAD

**Issue by benwbrum** [SlaveryImages/SlaveryImages.org#57]
The following items have duplicates:

- [x] A Slave Coffle at Rest, East Africa, Upper Nile Region, 1840s	2
- [x] Abdul Rahman (Rahaman), 1828	2
- [x] Africans Liberated from a Slave Ship, Jamaica, 1857	4
- [x] Africans Packed into a Slave Ship, 1857	2
- [ ] Africans Rescued from a Slave Ship, East Africa, 1869	2
- [x] An African Slave Flogs a Peruvian Indian, Peru, 1600-1615	2
- [x] Barber Shop, Richmond, Virginia, 1853	2
- [ ] Black Soldiers in the Union/Federal Army, ca. 1863-64	3
- [x] Brazilian Slave Ship Captured by British Navy, 1849	2
- [x] British Naval Vessel Chases a Slave Ship, 1850 	2
- [ ] Bush Negroes (Maroons), Suriname, ca. 1831	2
- [ ] Cape Coast Castle, Ghana, 1986	3
- [x] Capture of a Slave Ship, African Coast, 1857	2
- [x] Capture of a Slave Ship, African Coast, 1859	2
- [x] Captured Slave Ship, Jamaica, 1857	2
- [ ] Clothing of Enslaved Females, Rio de Janeiro, Brazil, ca. 1770s	2
- [ ] Clothing Styles, Senegal, 1806 	2
- [ ] Cooking Cauldron, Slave Ship Henrietta Marie, ca. 1697-1700	2
- [x] Cross-Section of Slave Ship, 1857	2
- [x] Elizabeth Freeman (a.k.a. Mumbat, Mum Bet), 1811	2
- [x] Ellen Kraft, a Fugitive Slave, 1851 	2
- [ ] Elmina Castle, Gold Coast, 1704	2
- [ ] Elmina Castle, Gold Coast, late 17th cent.	2
- [x] Enslaved Africans in a Coffle, Eastern Sudan, 1848	2
- [x] Enslaved Ethnic Groups, East Africa, Upper Nile Region, 1840s	2
- [x] Enslaved Females, Brazil, 1816-1831	2
- [x] Enslaved House Servants and White Children, South Carolina, 1863	2
- [x] Enslaved Men, Brazil, 1816-1831 	2
- [ ] Enslaved Woman, British West Indies, 1826	2
- [x] Exterior of Kitchen, Sierra Leone , 1856	2
- [ ] Female Clothing Styles, Paramaribo, Suriname, ca. 1831 	3
- [x] Festival, Havana, Cuba, 1847 	2
- [ ] Funeral, Angola, 1786-87	2
- [ ] Funeral, Brazil,1816-1831	2
- [x] House and Village Scene, Sierra Leone , 1856	2
- [x] House Construction and Roofing, Sierra Leone, 1856	2
- [x] House Servant, Baltimore, 1861	2
- [ ] Human Sacrificial Ceremony, Dahomey, 1849-50	2
- [ ] Indigo Manufacture, French West Indies, 18th cent.	2
- [ ] Interior of Kitchen, Sierra Leone, 1856	2
- [x] Job Ben Solomon (Ayuba Suleiman Diallo), 1750	2
- [ ] John Canoe (Jonkonnu, JonKanoo) Costume, Jamaica, 1837	2
- [ ] John Canoe (Jonkonnu, JonKanoo) Costume, Jamaica, 1838	2
- [ ] Le Negre Marron (The Black Maroon), Port-au-Prince, Haiti, 1970	2
- [ ] Male and Female Clothing Styles, Gold Coast, late 17th cent.	2
- [x] Marketplace and Houses, Sierra Leone, 1856	2
- [x] Olaudah Equiano or Ottobah Cugoano, late 18th cent.	2
- [x] Olaudah Equiano/Gustavas Vassa, 1791	2
- [x] Omar Ibn Said (Sayyid), mid-19th cent.	2
- [ ] Peddlers or Hawkers, Rio de Janeiro, Brazil, 1819-1820	2
- [x] Phillis Wheatley, ca. 1773	2
- [ ] Plantation Slaves, Beaufort, South Carolina, 1862	2
- [ ] Punishment in Stocks, Trinidad, 1836	2
- [ ] Revolt Aboard Slave Ship, 1787	2
- [ ] Revolt Aboard Slave Ship, 19th cent.	3
- [x] Shackles Used on Slave Ship, 1845 	2
- [ ] Slave Coffle, 19th cent.	2
- [x] Slave Coffle, Central Africa, 1874	2
- [x] Slave Coffle, East Africa, 1880s	2
- [x] Slave Coffle, East Africa, Upper Nile region, 1840s	2
- [x] Slave Ship, East African Coast, 1840s	2
- [x] Slave Trading Station, Mozambique, 1850 	2
- [x] Sleeping Position of Africans on Slave Ship, 1857	2
- [ ] Sugar Boiling House, Antigua, West Indies, 1823	2
- [ ] Sugar Plantation, St. Croix, Danish West Indies, ca. 1840	3
- [ ] Sugar Works and Plantation, Pernambuco, Brazil, ca. 1640	3
- [x] William Unsah Sessarakoo, ca. 1749	2
- [ ] Wooden Yokes Used in Coffles, Senegal, ca. 1789	2
- [x] Yarrow Mamout, 1819	2

**Comment by saracarl** [comment]
cleaned up all duplicates.  Many in the list above (the unchecked ones) had duplicate titles but different images -- in other words, they were of the same thing, but were not duplicates.
