### ISSUE TITLE
Some images do not load in Mirador

### ISSUE THREAD

**Issue by benwbrum** [SlaveryImages/SlaveryImages.org#67]
"Hawkers of Foodstufs in Gordonsville VA" does not load for some reason: http://mirador.britishart.yale.edu/?manifest=http://104.200.20.178/iiif/2897/manifest

**Comment by saracarl** [comment]
This is why:

 Exception
Failed to get image resolution: /var/www/html/files/original/32b8ed086a623e9f863bbd7556035dd4d9cb9c29.tif

Details:

Exception: Failed to get image resolution: /var/www/html/files/original/32b8ed086a623e9f863bbd7556035dd4d9cb9c29.tif in /var/www/html/modules/IiifServer/src/View/Helper/IiifManifest.php:1097
Stack trace:
#0 /var/www/html/modules/IiifServer/src/View/Helper/IiifManifest.php(649): Ii

**Comment by saracarl** [comment]
Better stack trace:
#0 /var/www/html/modules/IiifServer/src/View/Helper/IiifManifest.php(649): IiifServer\View\Helper\IiifManifest->_getImageSize(Object(Omeka\Api\Representation\MediaRepresentation), 'original')

**Comment by saracarl** [comment]
So the problem here is that we have the derivative large and medium images on the file system, but not the originals.  They were probably uploaded via the development server, and therefore were never there.

**Comment by saracarl** [comment]
Counts:

slaveryimages@slaveryimages:~/omeka_files/original$ ls -1 | wc -l
1066
slaveryimages@slaveryimages:~/omeka_files/original$ cd ../large
slaveryimages@slaveryimages:~/omeka_files/large$ ls -1 | wc -l
1255

**Comment by saracarl** [comment]
This is resolved -- was missing some derivative images.
